version: "3"
services:
  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    environment:
      - address=61184328cfd30d8caa78438884d5322ce203c045 #derived from the private key which is passed in the args
      - bootnodeId=enr:-KO4QN6ZWmGyrhhm8gvf-2kQfkxRNTVgAPhxvfdPX4tA3CIIVRfBcyT4_3d2ukCeTKbByUotav-LUzbqyWT-pBxonVeGAYWW5uTkg2V0aMfGhP-FS6eAgmlkgnY0gmlwhIm4QKuJc2VjcDI1NmsxoQNHZ5kjor-ok3f0zQ765YgQkSne9H4RaRpsdKNwUW-hCYRzbmFwwIN0Y3CCf5yDdWRwgn-c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=137.184.64.171
    build:
      context: .
      dockerfile: ./minerdeploy/Dockerfile
      args:
        privatekey: f8fe1beff5109x0x0x006484fd6e6f8617b251dcad7b4b9a724f26f5 # Please don't do something like this in production, okay?
        password: 123456
    ports:
      - 8546:8545
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address
    healthcheck:
      test: wget http://localhost:8546
      interval: 2s
      timeout: 5s
      retries: 30
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
